
---
- name: Pull docker image of Scientific Calculator
  hosts: all
  tasks:
    - name: Pull Calculator image
      docker_image:
        name: demonwolf1998/scientific-calculator
        source: pull